#!/bin/bash

LOG_DIR="/backup/engine/script/backuplog"
LOG_FILE="$LOG_DIR/$(date '+%Y-%m-%d').log"

# 로그 디렉토리가 없으면 생성
mkdir -p "$LOG_DIR"

# 로그 메시지 기록 함수
log_message() {
    local message="$1"
    echo "$(date '+%Y-%m-%d %H:%M:%S') $message" | tee -a "$LOG_FILE"
}

# 스크립트가 하나의 인자를 필요로 한다는 것을 확인
if [ $# -ne 1 ]; then
    log_message "Usage: $0 [start|stop]"
    exit 1
fi

# MySQL을 시작하는 함수 정의
start_mysql() {
    log_message "Starting MySQL..."
    while true; do
        if ! pgrep -f mysqld_safe > /dev/null; then
            /db/mysql/bin/mysqld_safe --defaults-file=/db/mysql/conf/my.cnf --ledir=/db/mysql/bin --mysqld=run_numa --user=mysql &
            sleep 20
            if pgrep -f mysqld_safe > /dev/null; then
                log_message "MySQL started successfully."
            else
                log_message "Failed to start MySQL."
            fi
        else
            log_message "MySQL is already running."
            exit 0
        fi
    done
}

# MySQL을 중지하는 함수 정의
stop_mysql() {
    log_message "Stopping MySQL..."
    RUN_CMD="/db/mysql/bin/mysqladmin --socket=/tmp/mysql.sock -pdlTlswo1030@ -ucondba shutdown"
    $RUN_CMD
    sleep 30
    log_message "MySQL stop command issued."

    for state in {1..3}; do
        CH_PROCESS=$(pgrep -f mysqld_safe | wc -l)
        CH_PORT=$(netstat -na | awk '$6 ~ /ESTABLISHED/ && $5 ~ /:34242$/ {print $0}' | wc -l)

        if [ $CH_PROCESS -gt 0 ] && [ $CH_PORT -gt 0 ]; then
            log_message "MySQL Daemon is still running"
            $RUN_CMD
            sleep 5
        elif [ $CH_PROCESS -eq 0 ] && [ $CH_PORT -ge 1 ]; then
            log_message "MySQL port is still running and state is abnormal"
            $RUN_CMD
            sleep 5
        elif [ $CH_PROCESS -ge 1 ] && [ $CH_PORT -eq 0 ]; then
            log_message "MySQL process is still running and state is abnormal"
            $RUN_CMD
            sleep 5
        else
            log_message "MySQL is down"
            break
        fi
    done

    if [ $CH_PROCESS -gt 0 ]; then
        log_message "MySQL stopping failed"
    fi
    if [ $CH_PORT -gt 0 ]; then
        log_message "MySQL stopping failed"
    fi
}

# 스크립트 인자에 따라 start 또는 stop 함수 호출
case "$1" in
    start)
        start_mysql
        ;;
    stop)
        stop_mysql
        ;;
    *)
        log_message "Usage: $0 [start|stop]"
        exit 1
        ;;
esac
