#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 param1 "
    exit -1
fi

if [ $1 = start ]; then
    echo "start mysql"
        while true
        do
                if [ `ps -ef |grep -i mysqld_safe|grep -v 'grep'|wc -l` -eq 0 ]; then
                        /db/mysql/bin/mysqld_safe --defaults-file=/db/mysql/conf/my.cnf --ledir=/db/mysql/bin  --mysqld=run_numa --user=mysql &
                        sleep 20
                else
                        echo "already start mysql"
                        exit
                fi
        done
elif [ $1 = stop ]; then
    echo "stop mysql"
        RUN_CMD="/db/mysql/bin/mysqladmin --socket=/tmp/mysql.sock -pdlTlswo1030@ -ucondba shutdown"
        ${RUN_CMD}
        sleep 30

        for state in 1 2 3
        do

                export CH_PROCESS=`ps -ef | grep -i mysqld_safe |grep -v 'grep'|wc -l`
                export CH_PORT=`netstat -na |awk '$6 ~ /ESTABLISHED/ && $5 ~ /:34242$/ {print $0}' |wc -l`

                if [ ${CH_PROCESS} -gt 0 -a ${CH_PORT} -gt 0 ];
                then
                        echo "MySQLDB Daemon  is still running"
                        ${RUN_CMD}
                        sleep 5
                elif [ ${CH_PROCESS} -eq 0 -a ${CH_PORT} -ge 1 ];
                then
                        echo "MySQLDB port is still running and stat is abnormal"
                        ${RUN_CMD}
                        sleep 5
                elif [ ${CH_PROCESS} -qe 1 -a ${CH_PORT} -eq 0 ];
                then
                        echo "MySQLDB Process is still running and stat is abnormal"
                        ${RUN_CMD}
                        sleep 5
                else
                        echo "MySQLDB is down"
                fi
        done;

        if [ $[CH_PROCESS] -gt 0 ];
        then
                echo "MySQLDB Stopping is Failed"

        fi
        if [ $[CH_PORT] -gt 0 ];
        then
                echo "MySQLDB Stopping is Failed"

        fi

else
    echo "Usage: $0 [start|stop]"
fi
